### Login
POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin123"
}

### Get Students (copy token from above response)
GET http://127.0.0.1:8000/api/students
Authorization: 25|9X4OhNgveg2vOXIs0KJbVQUVlBk3OBqbkgxaq669a6df22d3

### Create Student
POST http://127.0.0.1:8000/api/students
Content-Type: application/json

{
    "student_id": "22-10293",
    "first_name": "Amy",
    "middle_name": "Rivera",
    "last_name": "Castro",
    "year_level": "4th Year",
}

### Dashboard
GET http://127.0.0.1:8000/api/dashboard
Authorization: Bearer 4|WQHhN5NS58CapuyVqXPt17e3YPcfAUWUd2XVS1gUff3f212e

### Logout

POST http://127.0.0.1:8000/api/seed-term-balances
Authorization: Bearer 6|upyH3ibj3lXxph6XRwqYdlLpj1Lz0zt3Ad7vlE9Wca7f8343
Accept: application/json